In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  2 16:11:12 2019

@author: colinlaurence
"""
import geopandas as gp
import pandas as pd
import numpy as np
import fiona
import shapely
import datetime as dt
import matplotlib as plt
#import cartopy
import pyproj
from scipy.spatial import distance
import time

In [31]:
stops_df = pd.read_csv("vta_gtfs/stops.txt",header=0)
nodes_df = pd.read_csv("mobiliti_data/nodes_s_c.csv",header=0)

In [3]:



node_lat=nodes_df.lat[0]
node_lon=nodes_df.lng[0]
#print(node_lat)
def wgs2utm(row):
    myProj = pyproj.Proj("+proj=utm +zone=10S, +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
    xy=myProj(row['lng'], row['lat'], inverse=False)
    return np.array(xy)
    


#nodes_df['xy']= nodes_df.apply(wgs2utm,axis=1)
nodesxy=np.stack(nodes_df.apply(wgs2utm,axis=1))

stops_df.rename(columns={'stop_lat':'lat', 'stop_lon':'lng'}, inplace=True)
#stops_df['xy']= stops_df.apply(wgs2utm,axis=1)
stopsxy=np.stack(stops_df.apply(wgs2utm,axis=1))




    


In [6]:
dists=distance.cdist(stopsxy,nodesxy, 'euclidean')
processdone = time.time()
print(dists)

[[10022.97295623 10182.79696135 17861.86815733 ... 25787.21647456
  31346.79315565 26120.67236703]
 [11202.13545868 11283.78799431 14394.245415   ... 20616.44055495
  25323.45439721 28501.2701006 ]
 [ 9506.19515944  9586.45262233 16075.69150214 ... 19928.25666217
  24994.09061191 26802.21903069]
 ...
 [41645.04053037 41817.30880068 36700.81310993 ... 58886.76619891
  64087.05361097 51697.33395701]
 [41536.3797368  41708.6461375  36617.31633588 ... 58780.6071162
  63983.00537015 51592.24082486]
 [41303.2951228  41475.57305158 36414.23411043 ... 58545.91430936
  63749.86904475 51378.96243685]]


NameError: name 'setupdone' is not defined

In [7]:
closest_center=np.array([list(np.where(item == item.min())[0])[0] for item in dists])



In [10]:
closest_center[0:5]

array([129472,   1130,   1928, 138352,  32755])

In [11]:
nodesxy[0:5]

array([[  606649.62326023, 14131732.51566698],
       [  606571.44977783, 14131886.86947583],
       [  594482.78916395, 14109372.80670198],
       [  594559.42966556, 14109272.69700111],
       [  590122.5301304 , 14113508.01765876]])

In [13]:
stopsxy[0:5]

array([[  607374.74622821, 14121735.8070305 ],
       [  600165.22577357, 14122597.94243833],
       [  601066.82184526, 14124038.35718341],
       [  600806.74573596, 14125863.62665747],
       [  598866.12027832, 14129985.51739765]])

In [15]:
nodes_df[0:5]

Unnamed: 0          id            x            y       lat        lng  \
0         249  1013078525  606648.9942  4131732.508  37.32614 -121.79623   
1         250  1013078546  606570.9606  4131887.707  37.32754 -121.79709   
2         268  1006462339  594482.5871  4109373.392  37.12594 -121.93637   
3         269  1006462353  594559.0048  4109273.347  37.12503 -121.93552   
4         270  1006483322  590121.6858  4113508.918  37.16364 -121.98495   

    taz_id                     geometry  
0  27341.0  POINT (-121.79623 37.32614)  
1  27341.0  POINT (-121.79709 37.32754)  
2  27854.0  POINT (-121.93637 37.12594)  
3  27854.0  POINT (-121.93552 37.12503)  
4  27854.0  POINT (-121.98495 37.16364)

In [17]:
stops_df[0:5]

stop_id  stop_code                     stop_name  stop_desc        lat  \
0     4785      64785      SANTA TERESA STATION (1)        NaN  37.235966   
1     4735      64735           ALMADEN STATION (1)        NaN  37.244539   
2     4733      64733  OHLONE-CHYNOWETH STATION (1)        NaN  37.257423   
3     4780      64780           CAPITOL STATION (1)        NaN  37.273901   
4     4778      64778            TAMIEN STATION (1)        NaN  37.311257   

          lng  zone_id  
0 -121.789491        1  
1 -121.870638        1  
2 -121.860279        1  
3 -121.862964        1  
4 -121.884300        1

In [18]:
stopsxy[0]

array([  607374.74622821, 14121735.8070305 ])

In [19]:
nodesxy[129472]

array([  607344.6257142 , 14121600.45829421])

In [21]:
stopsxy[1]


array([  600165.22577357, 14122597.94243833])

In [30]:
nearest_node_id=[nodes_df['id'][i] for i in closest_center]

In [32]:
node_id=pd.DataFrame(nearest_node_id,columns=['node_id'])

index
0  129472
1    1130
2    1928
3  138352
4   32755

In [33]:
#near_pnts=[np.where(closest_center==i) for i in range(self.k)]
#new_centers=[np.mean(kmeans_obj.X[near_pnts[i]],axis=0) for i in range(self.k)]
stops_df.assign(node_id=node_id.values)

stop_id  stop_code                             stop_name  stop_desc  \
0        4785      64785              SANTA TERESA STATION (1)        NaN   
1        4735      64735                   ALMADEN STATION (1)        NaN   
2        4733      64733          OHLONE-CHYNOWETH STATION (1)        NaN   
3        4780      64780                   CAPITOL STATION (1)        NaN   
4        4778      64778                    TAMIEN STATION (1)        NaN   
5        4775      64775         CONVENTION CENTER STATION (1)        NaN   
6        4748      64748               SANTA CLARA STATION (0)        NaN   
7        4770      64770              CIVIC CENTER STATION (1)        NaN   
8        4753      64753             METRO/AIRPORT STATION (0)        NaN   
9        4765      64765               BONAVENTURA STATION (1)        NaN   
10       4762      64762                    TASMAN STATION (1)        NaN   
11       4797      64797             OLD IRONSIDES STATION (1)        NaN   
12       4799      64799                 LICK MILL STATION (1)        NaN   
13       4763      64763                RIVER OAKS STATION (1)        NaN   
14       4764      64764                   ORCHARD STATION (1)        NaN   
15       4766      64766                 COMPONENT STATION (1)        NaN   
16       4767      64767              KARINA COURT STATION (1)        NaN   
17       4752      64752                      GISH STATION (0)        NaN   
18       4798      64798             GREAT AMERICA STATION (1)        NaN   
19       4772      64772                  ST JAMES STATION (1)        NaN   
20       4771      64771            JAPANTOWN/AYER STATION (1)        NaN   
21       4736      64736              SANTA TERESA STATION (0)        NaN   
22       4737      64737                    COTTLE STATION (0)        NaN   
23       4738      64738                     SNELL STATION (0)        NaN   
24       4739      64739              BLOSSOM HILL STATION (0)        NaN   
25       4729      64729                   ALMADEN STATION (0)        NaN   
26       4730      64730                  OAKRIDGE STATION (0)        NaN   
27       4774      64774               SAN ANTONIO STATION (1)        NaN   
28       4776      64776    CHILDRENS DISCOVERY MUSEUM STA (1)        NaN   
29       4777      64777                  VIRGINIA STATION (1)        NaN   
...       ...        ...                                   ...        ...   
3825     4973      64973                         Murray & Taft        NaN   
3826      253      60253                       Forest & Walnut        NaN   
3827     5683      65683                       Forest & Walnut        NaN   
3828      249      60249                    Murray & Leavesley        NaN   
3829      250      60250                    Murray & Leavesley        NaN   
3830      251      60251                        Murray & Adams        NaN   
3831     5684      65684                    Murray & Leavesley        NaN   
3832     4974      64974                        Murray & Adams        NaN   
3833     4975      64975                    Murray & Leavesley        NaN   
3834     5685      65685                    Murray & Leavesley        NaN   
3835      243      60243                San Ysidro & Leavesley        NaN   
3836      247      60247                San Ysidro & Leavesley        NaN   
3837      246      60246               San Ysidro & Las Animas        NaN   
3838      244      60244               San Ysidro & Las Animas        NaN   
3839     5686      65686                      Murray & Madison        NaN   
3840      236      60236                      10th & Alexander        NaN   
3841      240      60240                         Kaiser Gilroy        NaN   
3842     5633      65633                  Valley Health Center        NaN   
3843     5661      65661  Camino Arroyo & Valley Health Center        NaN   
3844     5675      65675                   Camino Arroyo & 6th        NaN   
38

In [34]:
stops_df.to_csv(r'VTA_stops_with_node_ids.csv')